# Array Manipulation

In [122]:
import numpy as np

## Basic Indexing

1. Single Element Indexing

In [123]:
# Indexing the element of 1D array
x = np.arange(10)
print(x)
print(x[2])
print(x[-2])

[0 1 2 3 4 5 6 7 8 9]
2
8


2. Slicing and striding

In [124]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

In [125]:
print(x[-3:10])

print(x[-3:2:-1])


[7 8 9]
[7 6 5 4 3]


In [126]:
print(x[5:])
print(x[5::])

print(x[:5])
print(x[::5])


[5 6 7 8 9]
[5 6 7 8 9]
[0 1 2 3 4]
[0 5]


In [127]:
# Boolean indexing
bool_mask = x > 5

print(x[bool_mask])

[6 7 8 9]


In [128]:
# Fancy indexing
indices = np.array([0, 2, 4])
print(x[indices])

[0 2 4]


## Multi-dimensonal Indexing and Slicing

In [129]:
x = np.arange(10)
# Indexing the element of 2D array/matrix
x.shape = (2, 5) 
print(x)
print(x[1, 2]) # index 1 row(2nd row) and index 2 column(3rd column)

[[0 1 2 3 4]
 [5 6 7 8 9]]
7


In [130]:
# Indexing a multidimensional array with fewer indices than dimensions, we get a subdimensional array
x[0]

array([0, 1, 2, 3, 4])

In [131]:
# x[0][2] == x[0, 2] 
print(x[0][1])

print(x[0,1])
# second case is more inefficient as a new temporary array is created after first index which is subsequently indexed by 2

1
1


In [132]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Slices the first two rows and all columns after the first
arr[:2, 1:] 
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [133]:
# Creating a 2D array
x = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [137]:
# Indexing the rows from 1st row to 2nd row and all column
row_indices = np.array([0, 2])
print(x[row_indices, :])

[[1 2 3]
 [7 8 9]]


In [139]:
# Indexing elements using the boolean condition
bool_mask = x > 5
print(x[bool_mask])

[6 7 8 9]


In [141]:
# Creating a 3D array with shape (2, 3, 4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],

                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# Slicing along 1st layer of dimension, upto 2 rows and 3 columns form index 0
result = array_3d[0:1, 0:2, 0:3] 

print(result)

[[[1 2 3]
  [5 6 7]]]
